"""
Alert & Notification Tools

MCP tools to manage the background monitoring service and view alerts.
"""

import json
from typing import List

from mcp.server.fastmcp import FastMCP
from core.background_service import monitor

# --- Shared Tools ---

async def create_price_alert(symbol: str, target_price: float, condition: str = "ABOVE") -> str:
    """
    Set a price alert for a crypto asset.
    
    Args:
        symbol: e.g. "BTC"
        target_price: The trigger price
        condition: "ABOVE" or "BELOW"
        
    Returns:
        Confirmation message
    """
    message = f"Alert created for {symbol} {condition} {target_price}"
    # Use monitor to persist
    await monitor.add_alert(symbol, message, "INFO")
    return json.dumps({"status": "success", "message": message})

async def check_alerts(unread_only: bool = True) -> str:
    """
    Check for any new alerts generated by the background monitor.
    
    Args:
        unread_only: If True, only returns unread alerts.
    
    Returns:
        JSON string list of alerts.
    """
    # Lazy start the monitor if not already running
    await monitor.start()
    
    alerts = await monitor.get_alerts(unread_only=unread_only)
    
    return json.dumps({
        "count": len(alerts),
        "alerts": [dict(a) for a in alerts] # Convert Row to dict
    })

async def mark_alerts_read() -> str:
    """
    Mark all pending alerts as read.
    """
    await monitor.mark_all_read()
    return json.dumps({"status": "success", "message": "All alerts marked as read"})


def register_alert_tools(mcp: FastMCP) -> None:
    """
    Register Alert/Notification MCP tools.
    
    Args:
        mcp: FastMCP server instance
    """
    mcp.tool()(create_price_alert)
    mcp.tool()(check_alerts)
    mcp.tool()(mark_alerts_read)
