"""
Alert & Notification Tools

MCP tools to manage the background monitoring service and view alerts.
"""

import json
from typing import List

from mcp.server.fastmcp import FastMCP
from core.background_service import monitor

def register_alert_tools(mcp: FastMCP) -> None:
    """
    Register Alert/Notification MCP tools.
    
    Args:
        mcp: FastMCP server instance
    """
    
    @mcp.tool()
    async def check_alerts(unread_only: bool = True) -> str:
        """
        Check for any new alerts generated by the background monitor.
        
        Args:
            unread_only: If True, only returns unread alerts.
        
        Returns:
            JSON string list of alerts.
        """
        # Lazy start the monitor if not already running
        # (Since FastMCP might not have an easy startup hook)
        await monitor.start()
        
        alerts = monitor.get_alerts(unread_only=unread_only)
        
        # If checking unread, we usually mark them read after viewing? 
        # Or provide a separate tool? Let's auto-mark read if requested.
        # But this is a query, maybe side-effects are bad. 
        # Let's add a separate tool to clear.
        
        return json.dumps({
            "count": len(alerts),
            "alerts": alerts
        })

    @mcp.tool()
    def mark_alerts_read() -> str:
        """
        Mark all current alerts as read.
        """
        count = len(monitor.get_alerts(unread_only=True))
        monitor.mark_all_read()
        return json.dumps({"status": "success", "marked_read": count})

    @mcp.tool()
    def create_price_alert(symbol: str, target_price: float, condition: str = "ABOVE") -> str:
        """
        Set a price alert (Mock implementation for Phase 10).
        
        In a full implementation, this would update the watchlist in the background service.
        Currently, it logs the request and simulates a confirmation.
        
        Args:
            symbol: Asset symbol (e.g. BTC)
            target_price: Trigger price.
            condition: "ABOVE" or "BELOW".
        """
        # Feature placeholder
        monitor.add_alert("SYSTEM", f"Alert created for {symbol} {condition} {target_price}", "INFO")
        return json.dumps({
            "status": "created", 
            "message": f"Monitoring {symbol} for price {condition} {target_price}"
        })
